galaxy_info:
  author: Leif Madsen <leif@redhat.com>
  description: Service Telemetry Framework Umbrella Operator
  company: Red Hat, Inc.
  license: Apache
  min_ansible_version: 2.7

  platforms:
  - name: RHEL
    versions:
    - 7
  - name: CentOS
    versions:
    - 7

  galaxy_tags:
  - monitoring
  - servicetelemetry

dependencies: []

collections:
- operator_sdk.util
