apiVersion: infra.watch/v1alpha1
kind: ServiceTelemetry
metadata:
  name: stf-default
spec:
  metricsEnabled: true
  eventsEnabled: false
  highAvailabilityEnabled: false
  storageEphemeralEnabled: false
  graphingEnabled: false
  snmpTrapsEnabled: false
# vim: set ft=yaml shiftwidth=2 tabstop=2 expandtab:
