---
# vars file for servicetelemetry
servicetelemetry_vars:
  high_availability: |
    {%- if high_availability is defined and high_availability is iterable -%}
    {{ servicetelemetry_defaults.high_availability | combine((high_availability | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.high_availability }}
    {%- endif -%}
  alerting: |
    {%- if alerting is defined and alerting is iterable -%}
    {{ servicetelemetry_defaults.alerting | combine((alerting | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.alerting }}
    {%- endif -%}
  backends: |
    {%- if backends is defined and backends is iterable -%}
    {{ servicetelemetry_defaults.backends | combine((backends | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.backends }}
    {%- endif -%}
  transports: |
    {%- if transports is defined and transports is iterable -%}
    {{ servicetelemetry_defaults.transports | combine((transports | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.transports }}
    {%- endif -%}
  graphing: |
    {%- if graphing is defined and graphing is iterable -%}
    {{ servicetelemetry_defaults.graphing | combine((graphing | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.graphing }}
    {%- endif -%}
  clouds: |
    {%- if clouds is defined and clouds is iterable -%}
    {{ servicetelemetry_defaults.clouds | combine((clouds | stripnone), recursive=True) }}
    {%- else -%}
    {{ servicetelemetry_defaults.clouds }}
    {%- endif -%}
