- name: Deploy Metrics Smart Gateway instance for each agent
  vars:
    data_type: 'metrics'
    manifest: './manifest_smartgateway_metrics.j2'
  include_tasks: base_smartgateway.yml
  loop:
    - { name: 'Collectd', channel: 'collectd/telemetry'}
    - { name: 'Ceilometer', channel: 'anycast/ceilometer/metric.sample'}
  loop_control:
    loop_var: agent
    label: "{{ agent.name }}"
