- name: Create default Metrics Smart Gateway manifest
  set_fact:
    smartgateway_collectd_metrics_manifest: |
      apiVersion: smartgateway.infra.watch/v2alpha1
      kind: SmartGateway
      metadata:
        name: '{{ meta.name }}-collectd-telemetry'
        namespace: '{{ meta.namespace }}'
      spec:
        amqpUrl: '{{ meta.name }}-interconnect.{{ meta.namespace }}.svc.cluster.local:5672/collectd/telemetry'
        containerImagePath: 'quay.io/infrawatch/smart-gateway:latest'
        debug: {{ metrics_smart_gateway_collectd_debug_enabled }}
        serviceType: 'metrics'
        size: 1
        prefetch: 15000
        useTimestamp: true
  when: smartgateway_collectd_metrics_manifest is not defined

- name: Deploy instance of Smart Gateway for Collectd Metrics
  k8s:
    definition:
      '{{ smartgateway_collectd_metrics_manifest }}'
