- name: Create default Metrics Smart Gateway manifest
  set_fact:
    smartgateway_metrics_manifest: |
      apiVersion: smartgateway.infra.watch/v2alpha1
      kind: SmartGateway
      metadata:
        name: '{{ meta.name }}-telemetry'
        namespace: '{{ meta.namespace }}'
      spec:
        amqp_url: '{{ meta.name }}-interconnect.{{ meta.namespace }}.svc.cluster.local:5672/collectd/telemetry'
        container_image_path: 'quay.io/redhat-service-assurance/smart-gateway:latest'
        debug: 'false'
        service_type: 'metrics'
        size: 1
        prefetch: 15000
        use_timestamp: 'true'
  when: smartgateway_metrics_manifest is not defined

- name: Deploy instance of Smart Gateway for Metrics
  k8s:
    definition:
      '{{ smartgateway_metrics_manifest }}'
